modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"
issueTrackerURL = "https://github.com/halocore099/isotope/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
description = '''${mod_description}'''
authors = "${mod_author}"
logoFile = "assets/isotope/icon.png"
displayURL = "https://github.com/halocore099/isotope"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = "[15.0.0,)"
ordering = "NONE"
side = "BOTH"
